first_hour,first_min="6:52".split(":")
easy=8
tempo=6
easy_mile=3
tempo_mile=3
total=easy*easy_mile+tempo*tempo_mile
mid_min=int(first_min)+total
last_hour=int(first_hour)+mid_min//60
last_min=mid_min%60
print(str(last_hour)+":"+str(last_min))
